CREATE TABLE IF NOT EXISTS pacer_sortable_case_fields (
    field_name TEXT PRIMARY KEY
);

INSERT OR IGNORE INTO pacer_sortable_case_fields (field_name) VALUES
    ('courtId'),
    ('caseId'),
    ('caseYear'),
    ('caseNumber'),
    ('caseOffice'),
    ('caseType'),
    ('caseTitle'),
    ('dateFiled'),
    ('effectiveDateC'),
    ('closed'),
    ('dateReopened'),
    ('dateDismissed'),
    ('dateDischarged'),
    ('bankruptcyChapter'),
    ('dispositionMethod'),
    ('jointDispositionMethod'),
    ('jointDismissedDate'),
    ('jointDischargedDate'),
    ('jointBankruptcyFlag'),
    ('natureOfSuit'),
    ('jurisdictionType'),
    ('jpmlNumber'),
    ('mdlCourtId'),
    ('civilDateInitiate'),
    ('civilDateDisposition'),
    ('civilDateTerminated'),
    ('civilStatInitiated'),
    ('civilStatDisposition'),
    ('civilStatTerminated'),
    ('civilCtoNumber'),
    ('civilTransferee'),
    ('mdlExtension'),
    ('mdlTransfereeDistrict'),
    ('mdlLittype'),
    ('mdlStatus'),
    ('mdlDateReceived'),
    ('mdlDateOrdered'),
    ('mdlTransferee');
