CREATE TABLE IF NOT EXISTS pacer_courts (
    court_id TEXT PRIMARY KEY,
    court_name TEXT NOT NULL
);

INSERT OR IGNORE INTO pacer_courts (court_id, court_name) VALUES
    ('01bap', 'U.S. Court of Appeals, First Circuit BAP'),
    ('01ca', 'U.S. Court of Appeals, First Circuit'),
    ('02ca', 'U.S. Court of Appeals, Second Circuit'),
    ('03ca', 'U.S. Court of Appeals, Third Circuit'),
    ('04ca', 'U.S. Court of Appeals, Fourth Circuit'),
    ('05ca', 'U.S. Court of Appeals, Fifth Circuit'),
    ('06ca', 'U.S. Court of Appeals, Sixth Circuit'),
    ('07ca', 'U.S. Court of Appeals, Seventh Circuit'),
    ('08ca', 'U.S. Court of Appeals, Eighth Circuit'),
    ('09bap', 'U.S. Court of Appeals, Ninth Circuit BAP'),
    ('09ca', 'U.S. Court of Appeals, Ninth Circuit'),
    ('10ca', 'U.S. Court of Appeals, Tenth Circuit'),
    ('11ca', 'U.S. Court of Appeals, Eleventh Circuit'),
    ('akbk', 'Alaska Bankruptcy Court'),
    ('akdc', 'Alaska District Court'),
    ('almbk', 'Alabama Middle Bankruptcy Court'),
    ('almdc', 'Alabama Middle District Court'),
    ('alnbk', 'Alabama Northern Bankruptcy Court'),
    ('alndc', 'Alabama Northern District Court'),
    ('alsbk', 'Alabama Southern Bankruptcy Court'),
    ('alsdc', 'Alabama Southern District Court'),
    ('arebk', 'Arkansas Eastern Bankruptcy Court'),
    ('aredc', 'Arkansas Eastern District Court'),
    ('arwbk', 'Arkansas Western Bankruptcy Court'),
    ('arwdc', 'Arkansas Western District Court'),
    ('azbk', 'Arizona Bankruptcy Court'),
    ('azdc', 'Arizona District Court'),
    ('cacbk', 'California Central Bankruptcy Court'),
    ('cacdc', 'California Central District Court'),
    ('caebk', 'California Eastern Bankruptcy Court'),
    ('caedc', 'California Eastern District Court'),
    ('cafc', 'U.S. Court of Appeals, Federal Circuit'),
    ('canbk', 'California Northern Bankruptcy Court'),
    ('candc', 'California Northern District Court'),
    ('casbk', 'California Southern Bankruptcy Court'),
    ('casdc', 'California Southern District Court'),
    ('citdc', 'United States Court of International Trade'),
    ('cobk', 'Colorado Bankruptcy Court'),
    ('codc', 'Colorado District Court'),
    ('cofc', 'United States Federal Claims Court'),
    ('ctbk', 'Connecticut Bankruptcy Court'),
    ('ctdc', 'Connecticut District Court'),
    ('dcbk', 'District of Columbia Bankruptcy Court'),
    ('dcca', 'U.S. Court of Appeals, D.C. Circuit'),
    ('dcdc', 'District of Columbia District Court'),
    ('debk', 'Delaware Bankruptcy Court'),
    ('dedc', 'Delaware District Court'),
    ('flmbk', 'Florida Middle Bankruptcy Court'),
    ('flmdc', 'Florida Middle District Court'),
    ('flnbk', 'Florida Northern Bankruptcy Court'),
    ('flndc', 'Florida Northern District Court'),
    ('flsbk', 'Florida Southern Bankruptcy Court'),
    ('flsdc', 'Florida Southern District Court'),
    ('gambk', 'Georgia Middle Bankruptcy Court'),
    ('gamdc', 'Georgia Middle District Court'),
    ('ganbk', 'Georgia Northern Bankruptcy Court'),
    ('gandc', 'Georgia Northern District Court'),
    ('gasbk', 'Georgia Southern Bankruptcy Court'),
    ('gasdc', 'Georgia Southern District Court'),
    ('gubk', 'Guam Bankruptcy Court'),
    ('gudc', 'Guam District Court'),
    ('hibk', 'Hawaii Bankruptcy Court'),
    ('hidc', 'Hawaii District Court'),
    ('ianbk', 'Iowa Northern Bankruptcy Court'),
    ('iandc', 'Iowa Northern District Court'),
    ('iasbk', 'Iowa Southern Bankruptcy Court'),
    ('iasdc', 'Iowa Southern District Court'),
    ('idbk', 'Idaho Bankruptcy Court'),
    ('iddc', 'Idaho District Court'),
    ('ilcbk', 'Illinois Central Bankruptcy Court'),
    ('ilcdc', 'Illinois Central District Court'),
    ('ilnbk', 'Illinois Northern Bankruptcy Court'),
    ('ilndc', 'Illinois Northern District Court'),
    ('ilsbk', 'Illinois Southern Bankruptcy Court'),
    ('ilsdc', 'Illinois Southern District Court'),
    ('innbk', 'Indiana Northern Bankruptcy Court'),
    ('inndc', 'Indiana Northern District Court'),
    ('insbk', 'Indiana Southern Bankruptcy Court'),
    ('insdc', 'Indiana Southern District Court'),
    ('jpmldc', 'Judicial Panel on Multidistrict Litigation'),
    ('ksbk', 'Kansas Bankruptcy Court'),
    ('ksdc', 'Kansas District Court'),
    ('kyebk', 'Kentucky Eastern Bankruptcy Court'),
    ('kyedc', 'Kentucky Eastern District Court'),
    ('kywbk', 'Kentucky Western Bankruptcy Court'),
    ('kywdc', 'Kentucky Western District Court'),
    ('laebk', 'Louisiana Eastern Bankruptcy Court'),
    ('laedc', 'Louisiana Eastern District Court'),
    ('lambk', 'Louisiana Middle Bankruptcy Court'),
    ('lamdc', 'Louisiana Middle District Court'),
    ('lawbk', 'Louisiana Western Bankruptcy Court'),
    ('lawdc', 'Louisiana Western District Court'),
    ('mabk', 'Massachusetts Bankruptcy Court'),
    ('madc', 'Massachusetts District Court'),
    ('mdbk', 'Maryland Bankruptcy Court'),
    ('mddc', 'Maryland District Court'),
    ('mebk', 'Maine Bankruptcy Court'),
    ('medc', 'Maine District Court'),
    ('miebk', 'Michigan Eastern Bankruptcy Court'),
    ('miedc', 'Michigan Eastern District Court'),
    ('miwbk', 'Michigan Western Bankruptcy Court'),
    ('miwdc', 'Michigan Western District Court'),
    ('mnbk', 'Minnesota Bankruptcy Court'),
    ('mndc', 'Minnesota District Court'),
    ('moebk', 'Missouri Eastern Bankruptcy Court'),
    ('moedc', 'Missouri Eastern District Court'),
    ('mowbk', 'Missouri Western Bankruptcy Court'),
    ('mowdc', 'Missouri Western District Court'),
    ('msnbk', 'Mississippi Northern Bankruptcy Court'),
    ('msndc', 'Mississippi Northern District Court'),
    ('mssbk', 'Mississippi Southern Bankruptcy Court'),
    ('mssdc', 'Mississippi Southern District Court'),
    ('mtbk', 'Montana Bankruptcy Court'),
    ('mtdc', 'Montana District Court'),
    ('ncebk', 'North Carolina Eastern Bankruptcy Court'),
    ('ncedc', 'North Carolina Eastern District Court'),
    ('ncmbk', 'North Carolina Middle Bankruptcy Court'),
    ('ncmdc', 'North Carolina Middle District Court'),
    ('ncwbk', 'North Carolina Western Bankruptcy Court'),
    ('ncwdc', 'North Carolina Western District Court'),
    ('ndbk', 'North Dakota Bankruptcy Court'),
    ('nddc', 'North Dakota District Court'),
    ('nebk', 'Nebraska Bankruptcy Court'),
    ('nedc', 'Nebraska District Court'),
    ('nhbk', 'New Hampshire Bankruptcy Court'),
    ('nhdc', 'New Hampshire District Court'),
    ('njbk', 'New Jersey Bankruptcy Court'),
    ('njdc', 'New Jersey District Court'),
    ('nmbk', 'New Mexico Bankruptcy Court'),
    ('nmdc', 'New Mexico District Court'),
    ('nmidc', 'Northern Mariana Islands District Court'),
    ('nvbk', 'Nevada Bankruptcy Court'),
    ('nvdc', 'Nevada District Court'),
    ('nyebk', 'New York Eastern Bankruptcy Court'),
    ('nyedc', 'New York Eastern District Court'),
    ('nynbk', 'New York Northern Bankruptcy Court'),
    ('nyndc', 'New York Northern District Court'),
    ('nysbk', 'New York Southern Bankruptcy Court'),
    ('nysdc', 'New York Southern District Court'),
    ('nywbk', 'New York Western Bankruptcy Court'),
    ('nywdc', 'New York Western District Court'),
    ('ohnbk', 'Ohio Northern Bankruptcy Court'),
    ('ohndc', 'Ohio Northern District Court'),
    ('ohsbk', 'Ohio Southern Bankruptcy Court'),
    ('ohsdc', 'Ohio Southern District Court'),
    ('okebk', 'Oklahoma Eastern Bankruptcy Court'),
    ('okedc', 'Oklahoma Eastern District Court'),
    ('oknbk', 'Oklahoma Northern Bankruptcy Court'),
    ('okndc', 'Oklahoma Northern District Court'),
    ('okwbk', 'Oklahoma Western Bankruptcy Court'),
    ('okwdc', 'Oklahoma Western District Court'),
    ('orbk', 'Oregon Bankruptcy Court'),
    ('ordc', 'Oregon District Court'),
    ('paebk', 'Pennsylvania Eastern Bankruptcy Court'),
    ('paedc', 'Pennsylvania Eastern District Court'),
    ('pambk', 'Pennsylvania Middle Bankruptcy Court'),
    ('pamdc', 'Pennsylvania Middle District Court'),
    ('pawbk', 'Pennsylvania Western Bankruptcy Court'),
    ('pawdc', 'Pennsylvania Western District Court'),
    ('prbk', 'Puerto Rico Bankruptcy Court'),
    ('prdc', 'Puerto Rico District Court'),
    ('ribk', 'Rhode Island Bankruptcy Court'),
    ('ridc', 'Rhode Island District Court'),
    ('scbk', 'South Carolina Bankruptcy Court'),
    ('scdc', 'South Carolina District Court'),
    ('sdbk', 'South Dakota Bankruptcy Court'),
    ('sddc', 'South Dakota District Court'),
    ('tnebk', 'Tennessee Eastern Bankruptcy Court'),
    ('tnedc', 'Tennessee Eastern District Court'),
    ('tnmbk', 'Tennessee Middle Bankruptcy Court'),
    ('tnmdc', 'Tennessee Middle District Court'),
    ('tnwbk', 'Tennessee Western Bankruptcy Court'),
    ('tnwdc', 'Tennessee Western District Court'),
    ('txebk', 'Texas Eastern Bankruptcy Court'),
    ('txedc', 'Texas Eastern District Court'),
    ('txnbk', 'Texas Northern Bankruptcy Court'),
    ('txndc', 'Texas Northern District Court'),
    ('txsbk', 'Texas Southern Bankruptcy Court'),
    ('txsdc', 'Texas Southern District Court'),
    ('txwbk', 'Texas Western Bankruptcy Court'),
    ('txwdc', 'Texas Western District Court'),
    ('utbk', 'Utah Bankruptcy Court'),
    ('utdc', 'Utah District Court'),
    ('vaebk', 'Virginia Eastern Bankruptcy Court'),
    ('vaedc', 'Virginia Eastern District Court'),
    ('vawbk', 'Virginia Western Bankruptcy Court'),
    ('vawdc', 'Virginia Western District Court'),
    ('vibk', 'Virgin Islands Bankruptcy Court'),
    ('vidc', 'Virgin Islands District Court'),
    ('vtbk', 'Vermont Bankruptcy Court'),
    ('vtdc', 'Vermont District Court'),
    ('waebk', 'Washington Eastern Bankruptcy Court'),
    ('waedc', 'Washington Eastern District Court'),
    ('wawbk', 'Washington Western Bankruptcy Court'),
    ('wawdc', 'Washington Western District Court'),
    ('wiebk', 'Wisconsin Eastern Bankruptcy Court'),
    ('wiedc', 'Wisconsin Eastern District Court'),
    ('wiwbk', 'Wisconsin Western Bankruptcy Court'),
    ('wiwdc', 'Wisconsin Western District Court'),
    ('wvnbk', 'West Virginia Northern Bankruptcy Court'),
    ('wvndc', 'West Virginia Northern District Court'),
    ('wvsbk', 'West Virginia Southern Bankruptcy Court'),
    ('wvsdc', 'West Virginia Southern District Court'),
    ('wybk', 'Wyoming Bankruptcy Court'),
    ('wydc', 'Wyoming District Court');
