CREATE TABLE IF NOT EXISTS pacer_response_codes (
  http_status_code INTEGER PRIMARY KEY,
  reason_phrase TEXT NOT NULL,
  enum_name TEXT NOT NULL,
  application_usage TEXT NOT NULL,
  description TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS pacer_case_types (
  case_type_code TEXT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS pacer_courts (
  court_id TEXT PRIMARY KEY,
  court_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS pacer_sortable_case_fields (
  field_name TEXT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS pacer_sortable_party_fields (
  field_name TEXT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS search_regions (
  region_code TEXT PRIMARY KEY,
  region_name TEXT NOT NULL
);

INSERT INTO pacer_response_codes (http_status_code, reason_phrase, enum_name, application_usage, description) VALUES (200, 'OK', 'OK', 'Successful GET, HEAD, PUT, POST', 'The request has succeeded. For GET, the resource is returned in the body. For HEAD, headers only. For PUT or POST, the result of the action is returned.') ON CONFLICT DO NOTHING;
INSERT INTO pacer_response_codes (http_status_code, reason_phrase, enum_name, application_usage, description) VALUES (204, 'No Content', 'NO_CONTENT', 'Successful request with no response body', 'The server successfully processed the request and is not returning any content, but headers may be useful.') ON CONFLICT DO NOTHING;
INSERT INTO pacer_response_codes (http_status_code, reason_phrase, enum_name, application_usage, description) VALUES (400, 'Bad Request', 'BAD_REQUEST', 'Invalid argument, running exception, stopped state', 'The server could not understand the request due to invalid syntax or malformed input.') ON CONFLICT DO NOTHING;
INSERT INTO pacer_response_codes (http_status_code, reason_phrase, enum_name, application_usage, description) VALUES (401, 'Unauthorized', 'UNAUTHORIZED', 'User not authenticated', 'Authentication is required and has failed or has not yet been provided.') ON CONFLICT DO NOTHING;
INSERT INTO pacer_response_codes (http_status_code, reason_phrase, enum_name, application_usage, description) VALUES (404, 'Not Found', 'NOT_FOUND', 'Report not found', 'The server cannot find the requested resource. The endpoint may exist, but the resource does not.') ON CONFLICT DO NOTHING;
INSERT INTO pacer_response_codes (http_status_code, reason_phrase, enum_name, application_usage, description) VALUES (406, 'Not Acceptable', 'NOT_ACCEPTABLE', 'Validation exception', 'The server cannot produce a response matching the list of acceptable values defined by the client.') ON CONFLICT DO NOTHING;
INSERT INTO pacer_response_codes (http_status_code, reason_phrase, enum_name, application_usage, description) VALUES (429, 'Too Many Requests', 'TOO_MANY_REQUESTS', 'Too many reports running', 'The user has sent too many requests in a given amount of time, rate limiting.') ON CONFLICT DO NOTHING;
INSERT INTO pacer_response_codes (http_status_code, reason_phrase, enum_name, application_usage, description) VALUES (500, 'Internal Server Error', 'INTERNAL_SERVER_ERROR', 'Report failed, all other exceptions', 'The server encountered an unexpected condition that prevented it from fulfilling the request.') ON CONFLICT DO NOTHING;

INSERT INTO pacer_case_types (case_type_code) VALUES ('1453c') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('158d') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('2255') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('23f') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('ag') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('agen') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('agpet') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('ap') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('bail') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('bap') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('bk') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('bkcy') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('bkd') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('bkp') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('cafc') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('civil') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('cm') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('cr') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('crim') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('ct') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('cv') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('cv.pr') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('cv.us') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('cvpri') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('cvrgt') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('cvus') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('dcrim') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('dm') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('dp') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('dpw') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('hc') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('hc.st') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('img') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('ins') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('mand') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('mc') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('md') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('misc') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('mj') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('ml') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('mp') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('mr') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('ms') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('msop') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('mv') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('ncrim') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('ohndca') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('op') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('opus') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('other') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('pcd') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('pcf') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('po') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('pr') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('prici') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('prsw') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('prswo') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('prus') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('pt') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('r5.dc') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('rj') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('rvw') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('rvw.i') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('stp') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('tax') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('tp') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('usc') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('usp') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('vv') ON CONFLICT DO NOTHING;
INSERT INTO pacer_case_types (case_type_code) VALUES ('xc') ON CONFLICT DO NOTHING;

INSERT INTO pacer_courts (court_id, court_name) VALUES ('01bap', 'U.S. Court of Appeals, First Circuit BAP') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('01ca', 'U.S. Court of Appeals, First Circuit') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('02ca', 'U.S. Court of Appeals, Second Circuit') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('03ca', 'U.S. Court of Appeals, Third Circuit') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('04ca', 'U.S. Court of Appeals, Fourth Circuit') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('05ca', 'U.S. Court of Appeals, Fifth Circuit') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('06ca', 'U.S. Court of Appeals, Sixth Circuit') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('07ca', 'U.S. Court of Appeals, Seventh Circuit') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('08ca', 'U.S. Court of Appeals, Eighth Circuit') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('09bap', 'U.S. Court of Appeals, Ninth Circuit BAP') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('09ca', 'U.S. Court of Appeals, Ninth Circuit') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('10ca', 'U.S. Court of Appeals, Tenth Circuit') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('11ca', 'U.S. Court of Appeals, Eleventh Circuit') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('akbk', 'Alaska Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('akdc', 'Alaska District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('almbk', 'Alabama Middle Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('almdc', 'Alabama Middle District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('alnbk', 'Alabama Northern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('alndc', 'Alabama Northern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('alsbk', 'Alabama Southern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('alsdc', 'Alabama Southern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('arebk', 'Arkansas Eastern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('aredc', 'Arkansas Eastern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('arwbk', 'Arkansas Western Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('arwdc', 'Arkansas Western District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('azbk', 'Arizona Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('azdc', 'Arizona District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('cacbk', 'California Central Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('cacdc', 'California Central District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('caebk', 'California Eastern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('caedc', 'California Eastern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('cafc', 'U.S. Court of Appeals, Federal Circuit') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('canbk', 'California Northern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('candc', 'California Northern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('casbk', 'California Southern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('casdc', 'California Southern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('citdc', 'United States Court of International Trade') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('cobk', 'Colorado Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('codc', 'Colorado District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('cofc', 'United States Federal Claims Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('ctbk', 'Connecticut Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('ctdc', 'Connecticut District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('dcbk', 'District Of Columbia Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('dcca', 'U.S. Court of Appeals, D.C. Circuit') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('dcdc', 'District Of Columbia District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('debk', 'Delaware Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('dedc', 'Delaware District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('flmbk', 'Florida Middle Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('flmdc', 'Florida Middle District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('flnbk', 'Florida Northern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('flndc', 'Florida Northern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('flsbk', 'Florida Southern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('flsdc', 'Florida Southern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('gambk', 'Georgia Middle Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('gamdc', 'Georgia Middle District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('ganbk', 'Georgia Northern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('gandc', 'Georgia Northern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('gasbk', 'Georgia Southern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('gasdc', 'Georgia Southern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('gubk', 'Guam Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('gudc', 'Guam District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('hibk', 'Hawaii Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('hidc', 'Hawaii District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('ianbk', 'Iowa Northern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('iandc', 'Iowa Northern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('iasbk', 'Iowa Southern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('iasdc', 'Iowa Southern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('idbk', 'Idaho Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('iddc', 'Idaho District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('ilcbk', 'Illinois Central Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('ilcdc', 'Illinois Central District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('ilnbk', 'Illinois Northern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('ilndc', 'Illinois Northern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('ilsbk', 'Illinois Southern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('ilsdc', 'Illinois Southern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('innbk', 'Indiana Northern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('inndc', 'Indiana Northern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('insbk', 'Indiana Southern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('insdc', 'Indiana Southern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('jpmldc', 'Judicial Panel on Multidistrict Litigation') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('ksbk', 'Kansas Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('ksdc', 'Kansas District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('kyebk', 'Kentucky Eastern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('kyedc', 'Kentucky Eastern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('kywbk', 'Kentucky Western Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('kywdc', 'Kentucky Western District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('laebk', 'Louisiana Eastern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('laedc', 'Louisiana Eastern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('lambk', 'Louisiana Middle Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('lamdc', 'Louisiana Middle District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('lawbk', 'Louisiana Western Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('lawdc', 'Louisiana Western District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('mabk', 'Massachusetts Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('madc', 'Massachusetts District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('mdbk', 'Maryland Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('mddc', 'Maryland District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('mebk', 'Maine Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('medc', 'Maine District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('miebk', 'Michigan Eastern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('miedc', 'Michigan Eastern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('miwbk', 'Michigan Western Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('miwdc', 'Michigan Western District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('mnbk', 'Minnesota Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('mndc', 'Minnesota District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('moebk', 'Missouri Eastern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('moedc', 'Missouri Eastern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('mowbk', 'Missouri Western Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('mowdc', 'Missouri Western District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('msnbk', 'Mississippi Northern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('msndc', 'Mississippi Northern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('mssbk', 'Mississippi Southern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('mssdc', 'Mississippi Southern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('mtbk', 'Montana Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('mtdc', 'Montana District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('ncebk', 'North Carolina Eastern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('ncedc', 'North Carolina Eastern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('ncmbk', 'North Carolina Middle Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('ncmdc', 'North Carolina Middle District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('ncwbk', 'North Carolina Western Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('ncwdc', 'North Carolina Western District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('ndbk', 'North Dakota Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('nddc', 'North Dakota District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('nebk', 'Nebraska Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('nedc', 'Nebraska District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('nhbk', 'New Hampshire Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('nhdc', 'New Hampshire District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('njbk', 'New Jersey Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('njdc', 'New Jersey District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('nmbk', 'New Mexico Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('nmdc', 'New Mexico District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('nmidc', 'Northern Mariana Islands District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('nvbk', 'Nevada Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('nvdc', 'Nevada District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('nyebk', 'New York Eastern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('nyedc', 'New York Eastern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('nynbk', 'New York Northern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('nyndc', 'New York Northern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('nysbk', 'New York Southern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('nysdc', 'New York Southern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('nywbk', 'New York Western Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('nywdc', 'New York Western District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('ohnbk', 'Ohio Northern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('ohndc', 'Ohio Northern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('ohsbk', 'Ohio Southern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('ohsdc', 'Ohio Southern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('okebk', 'Oklahoma Eastern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('okedc', 'Oklahoma Eastern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('oknbk', 'Oklahoma Northern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('okndc', 'Oklahoma Northern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('okwbk', 'Oklahoma Western Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('okwdc', 'Oklahoma Western District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('orbk', 'Oregon Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('ordc', 'Oregon District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('paebk', 'Pennsylvania Eastern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('paedc', 'Pennsylvania Eastern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('pambk', 'Pennsylvania Middle Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('pamdc', 'Pennsylvania Middle District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('pawbk', 'Pennsylvania Western Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('pawdc', 'Pennsylvania Western District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('prbk', 'Puerto Rico Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('prdc', 'Puerto Rico District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('ribk', 'Rhode Island Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('ridc', 'Rhode Island District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('scbk', 'South Carolina Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('scdc', 'South Carolina District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('sdbk', 'South Dakota Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('sddc', 'South Dakota District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('tnebk', 'Tennessee Eastern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('tnedc', 'Tennessee Eastern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('tnmbk', 'Tennessee Middle Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('tnmdc', 'Tennessee Middle District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('tnwbk', 'Tennessee Western Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('tnwdc', 'Tennessee Western District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('txebk', 'Texas Eastern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('txedc', 'Texas Eastern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('txnbk', 'Texas Northern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('txndc', 'Texas Northern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('txsbk', 'Texas Southern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('txsdc', 'Texas Southern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('txwbk', 'Texas Western Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('txwdc', 'Texas Western District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('utbk', 'Utah Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('utdc', 'Utah District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('vaebk', 'Virginia Eastern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('vaedc', 'Virginia Eastern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('vawbk', 'Virginia Western Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('vawdc', 'Virginia Western District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('vibk', 'Virgin Islands Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('vidc', 'Virgin Islands District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('vtbk', 'Vermont Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('vtdc', 'Vermont District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('waebk', 'Washington Eastern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('waedc', 'Washington Eastern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('wawbk', 'Washington Western Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('wawdc', 'Washington Western District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('wiebk', 'Wisconsin Eastern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('wiedc', 'Wisconsin Eastern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('wiwbk', 'Wisconsin Western Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('wiwdc', 'Wisconsin Western District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('wvnbk', 'West Virginia Northern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('wvndc', 'West Virginia Northern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('wvsbk', 'West Virginia Southern Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('wvsdc', 'West Virginia Southern District Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('wybk', 'Wyoming Bankruptcy Court') ON CONFLICT DO NOTHING;
INSERT INTO pacer_courts (court_id, court_name) VALUES ('wydc', 'Wyoming District Court') ON CONFLICT DO NOTHING;

INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('courtId') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('caseId') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('caseYear') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('caseNumber') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('caseOffice') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('caseType') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('caseTitle') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('dateFiled') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('effectiveDateClosed') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('dateReopened') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('dateDismissed') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('dateDischarged') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('bankruptcyChapter') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('dispositionMethod') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('jointDispositionMethod') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('jointDismissedDate') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('jointDischargedDate') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('jointBankruptcyFlag') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('natureOfSuit') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('jurisdictionType') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('jpmlNumber') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('mdlCourtId') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('civilDateInitiate') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('civilDateDisposition') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('civilDateTerminated') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('civilStatInitiated') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('civilStatDisposition') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('civilStatTerminated') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('civilCtoNumber') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('civilTransferee') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('mdlExtension') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('mdlTransfereeDistrict') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('mdlLittype') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('mdlStatus') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('mdlDateReceived') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('mdlDateOrdered') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_case_fields (field_name) VALUES ('mdlTransferee') ON CONFLICT DO NOTHING;

INSERT INTO pacer_sortable_party_fields (field_name) VALUES ('courtId') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_party_fields (field_name) VALUES ('caseId') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_party_fields (field_name) VALUES ('caseYear') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_party_fields (field_name) VALUES ('caseNumber') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_party_fields (field_name) VALUES ('lastName') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_party_fields (field_name) VALUES ('firstName') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_party_fields (field_name) VALUES ('middleName') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_party_fields (field_name) VALUES ('generation') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_party_fields (field_name) VALUES ('partyType') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_party_fields (field_name) VALUES ('role') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_party_fields (field_name) VALUES ('jurisdictionType') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_party_fields (field_name) VALUES ('seqNo') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_party_fields (field_name) VALUES ('aliasEq') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_party_fields (field_name) VALUES ('aliasType') ON CONFLICT DO NOTHING;
INSERT INTO pacer_sortable_party_fields (field_name) VALUES ('description') ON CONFLICT DO NOTHING;

INSERT INTO search_regions (region_code, region_name) VALUES ('01', 'First Circuit') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('02', 'Second Circuit') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('03', 'Third Circuit') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('04', 'Fourth Circuit') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('05', 'Fifth Circuit') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('06', 'Sixth Circuit') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('07', 'Seventh Circuit') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('08', 'Eighth Circuit') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('09', 'Ninth Circuit') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('10', 'Tenth Circuit') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('11', 'Eleventh Circuit') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('cafc', 'Federal Circuit') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('dcca', 'D.C. Circuit') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('al', 'Alabama') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('alm', 'Alabama Middle') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('aln', 'Alabama Northern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('als', 'Alabama Southern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('ak', 'Alaska') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('az', 'Arizona') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('ar', 'Arkansas') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('are', 'Arkansas Eastern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('arw', 'Arkansas Western') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('ca', 'California') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('cac', 'California Central') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('cae', 'California Eastern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('can', 'California Northern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('cas', 'California Southern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('cofc', 'Federal Claims') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('co', 'Colorado') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('ct', 'Connecticut') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('dc', 'District of Columbia') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('de', 'Delaware') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('fl', 'Florida') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('flm', 'Florida Middle') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('fln', 'Florida Northern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('fls', 'Florida Southern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('ga', 'Georgia') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('gam', 'Georgia Middle') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('gan', 'Georgia Northern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('gas', 'Georgia Southern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('gu', 'Guam') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('hi', 'Hawaii') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('id', 'Idaho') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('il', 'Illinois') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('ilc', 'Illinois Central') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('iln', 'Illinois Northern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('ils', 'Illinois Southern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('in', 'Indiana') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('inn', 'Indiana Northern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('ins', 'Indiana Southern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('ia', 'Iowa') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('ian', 'Iowa Northern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('ias', 'Iowa Southern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('ks', 'Kansas') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('ky', 'Kentucky') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('kye', 'Kentucky Eastern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('kyw', 'Kentucky Western') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('la', 'Louisiana') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('lae', 'Louisiana Eastern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('lam', 'Louisiana Middle') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('law', 'Louisiana Western') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('me', 'Maine') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('md', 'Maryland') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('ma', 'Massachusetts') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('mi', 'Michigan') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('mie', 'Michigan Eastern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('miw', 'Michigan Western') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('mn', 'Minnesota') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('ms', 'Mississippi') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('msn', 'Mississippi Northern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('mss', 'Mississippi Southern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('mo', 'Missouri') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('moe', 'Missouri Eastern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('mow', 'Missouri Western') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('mt', 'Montana') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('ne', 'Nebraska') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('nv', 'Nevada') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('nh', 'New Hampshire') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('nj', 'New Jersey') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('nm', 'New Mexico') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('ny', 'New York') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('nye', 'New York Eastern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('nyn', 'New York Northern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('nys', 'New York Southern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('nyw', 'New York Western') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('nc', 'North Carolina') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('nce', 'North Carolina Eastern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('ncm', 'North Carolina Middle') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('ncw', 'North Carolina Western') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('nd', 'North Dakota') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('nmi', 'Northern Mariana Islands') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('oh', 'Ohio') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('ohn', 'Ohio Northern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('ohs', 'Ohio Southern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('ok', 'Oklahoma') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('oke', 'Oklahoma Eastern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('okn', 'Oklahoma Northern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('okw', 'Oklahoma Western') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('or', 'Oregon') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('pa', 'Pennsylvania') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('pae', 'Pennsylvania Eastern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('pam', 'Pennsylvania Middle') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('paw', 'Pennsylvania Western') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('pr', 'Puerto Rico') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('ri', 'Rhode Island') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('sc', 'South Carolina') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('sd', 'South Dakota') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('tn', 'Tennessee') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('tne', 'Tennessee Eastern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('tnm', 'Tennessee Middle') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('tnw', 'Tennessee Western') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('tx', 'Texas') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('txe', 'Texas Eastern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('txn', 'Texas Northern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('txs', 'Texas Southern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('txw', 'Texas Western') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('ut', 'Utah') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('vt', 'Vermont') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('vi', 'Virgin Islands') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('va', 'Virginia') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('vae', 'Virginia Eastern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('vaw', 'Virginia Western') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('wa', 'Washington') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('wae', 'Washington Eastern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('waw', 'Washington Western') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('wv', 'West Virginia') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('wvn', 'West Virginia Northern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('wvs', 'West Virginia Southern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('wi', 'Wisconsin') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('wie', 'Wisconsin Eastern') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('wiw', 'Wisconsin Western') ON CONFLICT DO NOTHING;
INSERT INTO search_regions (region_code, region_name) VALUES ('wy', 'Wyoming') ON CONFLICT DO NOTHING;
